EShop/EShop.WebUI/Areas/Admin/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EShop.WebUI.Areas.Admin.Controllers
{
    public class ManagerController : BasicController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PartialHeader()
        {
            return View();
        }

        public ActionResult PartialFooter()
        {
            return View();
        }
    }
}

EShop/EShop.WebUI/Areas/Admin/Views/Shared/Pagination.cshtml
@model IPagination
@{
    Layout = null;
}

@{
    RouteValueDictionary oldRouteValueDict = null;
    var parentRouteValues = this.ViewContext.RouteData.Values["parentRouteValues"];
    if (parentRouteValues != null)
    {
        oldRouteValueDict = parentRouteValues as RouteValueDictionary;
    }
    else
    {
        oldRouteValueDict = Url.RouteValues().AppendOrReplace("parentRouteValues", null);
    }
    var firstLink = Url.RouteUrl(oldRouteValueDict.AppendOrReplace("page", 1));
    var prevPageLink = Url.RouteUrl(oldRouteValueDict.AppendOrReplace("page", Model.CurrentPage - 1));
    var nextPageLink = Url.RouteUrl(oldRouteValueDict.AppendOrReplace("page", Model.CurrentPage + 1));
    var endLink = Url.RouteUrl(oldRouteValueDict.AppendOrReplace("page", Model.PageCount));
    
    
}
@{
    System.Text.StringBuilder sb = new System.Text.StringBuilder();

    sb.AppendFormat("<div class=\"col-lg-6\"><div class=\"pagination-panel\" style=\"padding-top: 7px;\">当前{0}页，总共{1}页，总共{2}条数据</div></div>", Model.CurrentPage, Model.PageCount, Model.DataCount);
    
    sb.AppendFormat("<div class=\"col-lg-6 text-right\"><div class=\"pagination-panel\"><ul class=\"pagination pagination-sm man\">");
    if (Model.CurrentPage == 1)
    {
        sb.Append("<li class=\"disabled\"><a>首页</a></li>");
        sb.Append("<li class=\"disabled\"><a>上一页</a></li>");
    }
    else
    {
        sb.AppendFormat("<li><a href=\"{0}\">首页</a></li>", firstLink);
        sb.AppendFormat("<li><a href=\"{0}\">上一页</a></li>", prevPageLink);
    }
   
    @PageList()
    for (int i = ViewBag.Start; i <= ViewBag.End; i++)
    {
        var currentLink = Url.RouteUrl(oldRouteValueDict.AppendOrReplace("page", i));
        if (Model.CurrentPage == i)
        {
            sb.AppendFormat("<li class=\"active\"><a href=\"{0}\">" + i + "</a></li>", currentLink);
        }
        else
        {
            sb.AppendFormat("<li><a href=\"{0}\">" + i + "</a></li>", currentLink);
        }
    }

    if (Model.CurrentPage == Model.PageCount)
    {
        sb.Append("<li class=\"disabled\"><a>下一页</a></li>");
        sb.Append("<li class=\"disabled\"><a>尾页</a></li>");
    }
    else
    {
        sb.AppendFormat("<li><a href=\"{0}\">下一页</a></li>", nextPageLink);
        sb.AppendFormat("<li><a href=\"{0}\">尾页</a></li>", endLink);
    }

    //sb.AppendFormat("<li>第{0}页</span><span>共 {1} 页</li>", Model.CurrentPage, Model.PageCount);
    sb.AppendFormat("</ul></div></div>");
        
}
@Html.Raw(sb)


@helper PageList()
{
    int start = 1, end = 10;///
    if (Model.PageCount < end)//页数小于10
    {
        end = Model.PageCount;
    }
    else
    {
        start = (Model.CurrentPage > 5) ? Model.CurrentPage - 5 : start;
        int result = (start + 9) - Model.PageCount;//是否超过最后面的页数
        if (result > 0)
        {
            end = Model.PageCount;
            start -= result;//超过后,补差
        }
        else
        {
            end = start + 9;
        }
    }
    ViewBag.Start = start;
    ViewBag.End = end;
}

EShop/EShop.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="cache-control" content="no-cache">
    <title>@ViewBag.Title - EShop后台管理系统</title>

    <link href="/content/mgr/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    @Styles.Render("~/content/manager/css")

    <!-- 加载插件样式 -->
    @RenderSection("styles", required: false)

    @Styles.Render("~/content/manager/css/themes")
</head>
<body>
    @Html.Action("PartialHeader", "Manager", new { area = "Admin" })

    <div id="wrapper">
        <!-- 左侧菜单 start -->
        <nav id="sidebar" role="navigation" class="navbar-default navbar-static-side">
            <div class="sidebar-collapse menu-scroll">
                <ul id="side-menu" class="nav">
                    <li class="user-panel">
                        <div class="thumb">
                            <img src="~/content/mgr/images/gallery/data/head_default.jpg" class="img-circle" />
                        </div>
                        <div class="info">
                            <p>@User.Identity.Name.ToDescription(6)</p>
                            <ul class="list-inline list-unstyled">
                                <li><a href="/home/basicinfo" title="基本信息"><i class="fa fa-user"></i></a></li>
                                <li><a href="javascript:void(0);" title="邮件通知"><i class="fa fa-envelope"></i></a></li>
                                <li><a href="javascript:void(0);" class="js-password" title="修改密码"><i class="fa fa-cog"></i></a></li>
                                <li><a href="javascript:void(0);" class="js-exit" title="用户退出"><i class="fa fa-sign-out"></i></a></li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                    <li class="amy-menu-default">
                        <a href="/admin/manager">
                            <i class="fa fa-tachometer fa-fw">
                                <div class="icon-bg bg-orange"></div>
                            </i>
                            <span class="menu-title">我的工作台</span>
                        </a>
                    </li>
                    <li data-cookie="system">
                        <a href="javascript:void(0);">
                            <i class="fa fa-laptop fa-fw">
                                <div class="icon-bg bg-pink"></div>
                            </i>
                            <span class="menu-title">系统管理</span><span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li data-cookie="system-roles" class="amy-menu"><a href="/admin/role"><i class="fa fa-rocket"></i><span class="submenu-title">角色列表</span></a></li>
                        </ul>
                    </li>
                    <li data-cookie="member">
                        <a href="javascript:void(0);">
                            <i class="fa fa-laptop fa-fw">
                                <div class="icon-bg bg-pink"></div>
                            </i>
                            <span class="menu-title">会员管理</span><span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li data-cookie="member-list" class="amy-menu"><a href="/admin/member"><i class="fa fa-rocket"></i><span class="submenu-title">会员列表</span></a></li>
                        </ul>
                    </li>
                    <li data-cookie="goods">
                        <a href="javascript:void(0);">
                            <i class="fa fa-laptop fa-fw">
                                <div class="icon-bg bg-pink"></div>
                            </i>
                            <span class="menu-title">商品管理</span><span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li data-cookie="goods-list" class="amy-menu"><a href="/admin/member"><i class="fa fa-rocket"></i><span class="submenu-title">上架商品</span></a></li>
                            <li data-cookie="goods-list" class="amy-menu"><a href="/admin/member"><i class="fa fa-rocket"></i><span class="submenu-title">商品列表</span></a></li>
                            <li data-cookie="goods-category" class="amy-menu"><a href="/admin/member"><i class="fa fa-rocket"></i><span class="submenu-title">分类列表</span></a></li>
                            <li data-cookie="goods-brand" class="amy-menu"><a href="/admin/member"><i class="fa fa-rocket"></i><span class="submenu-title">品牌列表</span></a></li>
                            <li data-cookie="goods-property" class="amy-menu"><a href="/admin/member"><i class="fa fa-rocket"></i><span class="submenu-title">属性规格</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- 左侧菜单 end -->
        <!-- 内容区域 start -->
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- 内容区域 end -->
    </div>

    @Html.Action("PartialFooter", "Manager", new { area="Admin" })

    @RenderSection("scripts", required: false)
</body>
</html>